version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'python3'
    ports:
      - "8000:8000"
    working_dir: '/root/'
    tty: true
    volumes:
      - ./src:/root/src/
      - ~/.zshrc:/root/.zshrc
